import ad1 from './systems_ad_1.jpg';
import ad2 from './systems_ad_2.jpg';
import ad3 from './systems_ad_3.jpg';
import autp1 from './systems_autp_1.jpg';
import autp2 from './systems_autp_2.jpg';
import cool1 from './systems_cool_1.jpg';
import et1 from './systems_et_1.jpg';
import et2 from './systems_et_2.jpg';
import et3 from './systems_et_3.jpg';
import ht1 from './systems_ht_1.jpg';
import ht2 from './systems_ht_2.jpg';
import it1 from './systems_it_1.jpg';
import it2 from './systems_it_2.jpg';
import it3 from './systems_it_3.jpg';
import lt1 from './systems_lt_1.jpg';
import lt2 from './systems_lt_2.jpg';
import odn1 from './systems_odn_1.jpg';
import odn2 from './systems_odn_2.jpg';
import sa1 from './systems_sa_1.jpg';
import sa2 from './systems_sa_2.jpg';

export {ad1, ad2, ad3, autp1, autp2, cool1, et1, et2, et3, ht1, ht2, it1, it2, it3, lt1, lt2, odn1, odn2, sa1, sa2};